name: aviation_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.1
  fl_chart: ^0.50.1
  flutter:
    sdk: flutter
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
