name: aviation_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.5
  fl_chart: ^0.50.6
  flutter:
    sdk: flutter
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
